sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t 510ravikothari/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 510ravikothari/react-test npm test

after_success:
  - docker build -t 510ravikothari/multi-client ./client
  - docker build -t 510ravikothari/multi-nginx ./nginx
  - docker build -t 510ravikothari/multi-server ./server
  - docker build -t 510ravikothari/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 510ravikothari/multi-client
  - docker push 510ravikothari/multi-nginx
  - docker push 510ravikothari/multi-server
  - docker push 510ravikothari/multi-worker
